### ISSUE TITLE
piston pyton libraries voting fail

### ISSUE THREAD

**Issue by MarcGodard** [Netherdrake/steemtools#2]
Once I install this, when I use the piston tool or library in a script for voting, I always get a broadcast error... Even though the vote went through.

This means I can't tell between a real error and one of these errors.

I installed everything on my user (nothing global) on a centOS server.

**Comment by Netherdrake** [comment]
Voting is handled by piston:
https://github.com/xeroc/piston/tree/develop

I do not see any recent changes that could impact votes. 

The only case when I've seen this error is when the account has very few vests (SP), and tries to cast a fractional vote, which puts it below network required threshold.

**Comment by MarcGodard** [comment]
I would think that would be it, however it is every vote. And I got it working on my desktop by reinstalling the non-dev piston after your tools (and the extra dev piston) both work on my desktop. It is just my server. This isn't recent either, its been since the beginning (was running the voting off my desktop but want to move it)

**Comment by MarcGodard** [comment]
I should add that on my desktop its all done with an admin account. On my server it is done with a user account. That is really the only difference.

Is there a way to get more details of the error? I get a broadcast error and it is the same if the vote works or not.

**Comment by Netherdrake** [comment]
As far as I know, root privileges are not required.

You can see how BroadcastingError works here:
https://github.com/xeroc/piston/blob/75d5d7c87eb1b86d93253339ec90c80dc181152a/piston/steem.py#L480-L485

You can try constructing the voting transaction manually, and see what error is returned by Steem's RPC.

**Comment by MarcGodard** [comment]
Ok, I will look deeper in it... was hoping this was known.

**Comment by MarcGodard** [comment]
I started another server from scratch and got it to work. Might have been a strange bug on the old server.
