### ISSUE TITLE
fork for GOLOS chain

### ISSUE THREAD

**Issue by cryptomental** [Netherdrake/steemtools#4]
Hi, I forked Steemtools to make it compatible with Golos chain. Not many changes are needed apart from hardcoded SDB/STEEM/VESTS, perhaps in the future we could merge it into a common repo for 'social chains'. I suspect though that Golos may have a set of different features in the future and for now we can keep it separate.

I would like to leave the license and you as the main author and add myself in the fork as a maintainer. Please let me know if you are fine with this.
Best regards,
Przemek (@cryptomental)

**Comment by Netherdrake** [comment]
Thank you for being awesome :)
